//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using ChatModule;
using PublicModule;
using ConsumerModule;

namespace ConsumerApi
{
    public partial interface IConsumerApi : IChatModuleClient, IPublicModuleClient, IConsumerModuleClient
    {
        // All methods inherited from module client interfaces
    }
}