
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SharedSchemaRepo;
public partial interface ICategoryRepo : IDocumentRepo<Category> {}
public partial class CategoryRepo : DYDBRepository<Category>, ICategoryRepo
{
    public CategoryRepo(IAmazonDynamoDB client) : base(client) {}

    // From the Category schema's x-lz-tablelevel and x-lz-tablekind; LazyMagic's defaults when absent.
    protected override TableLevel TableLevel => TableLevel.Default;
    protected override TableKind TableKind => TableKind.Lsi;
}
