
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace SharedSchemaRepo;
public partial interface IPetRepo : IDocumentRepo<Pet> {}
public partial class PetRepo : DYDBRepository<Pet>, IPetRepo
{
    public PetRepo(IAmazonDynamoDB client) : base(client) {}

    // From the Pet schema's x-lz-tablelevel and x-lz-tablekind; LazyMagic's defaults when absent.
    protected override TableLevel TableLevel => TableLevel.Default;
    protected override TableKind TableKind => TableKind.Lsi;
}
