// Generated by LazyMagic - modifications will be overwritten
using System.Text.Json.Serialization;

namespace StoreEventsApi;

public class SessionEvent
{
    [JsonPropertyName("type")]
    public string Type { get; set; } = string.Empty;

    [JsonPropertyName("timestamp")]
    public DateTime Timestamp { get; set; } = DateTime.UtcNow;

    [JsonPropertyName("sessionId")]
    public string SessionId { get; set; } = string.Empty;

    [JsonPropertyName("data")]
    public object? Data { get; set; }
}

public class ChatMessageEvent : SessionEvent
{
    public ChatMessageEvent()
    {
        Type = "ChatMessage";
    }

    [JsonPropertyName("message")]
    public string Message { get; set; } = string.Empty;

    [JsonPropertyName("role")]
    public string Role { get; set; } = string.Empty;
}

public class SessionStatusEvent : SessionEvent
{
    public SessionStatusEvent()
    {
        Type = "SessionStatus";
    }

    [JsonPropertyName("status")]
    public string Status { get; set; } = string.Empty;
}

public class ErrorEvent : SessionEvent
{
    public ErrorEvent()
    {
        Type = "Error";
    }

    [JsonPropertyName("error")]
    public string Error { get; set; } = string.Empty;
}