// Generated by LazyMagic - modifications will be overwritten
using Amazon.AppSync;
using Amazon.Extensions.NETCore.Setup;
using Microsoft.Extensions.DependencyInjection;

namespace TenantEventsApi;

public static class ServiceCollectionExtensions
{
    public static IServiceCollection AddAppSyncEventsClient(this IServiceCollection services)
    {
        services.AddAWSService<IAmazonAppSync>();
        services.AddScoped<IAppSyncEventsClient, AppSyncEventsClient>();
        return services;
    }

    public static IServiceCollection AddAppSyncEventsClient(this IServiceCollection services, string eventApiId)
    {
        services.AddAWSService<IAmazonAppSync>();
        services.AddScoped<IAppSyncEventsClient>(provider =>
        {
            var appSyncClient = provider.GetRequiredService<IAmazonAppSync>();
            var logger = provider.GetRequiredService<Microsoft.Extensions.Logging.ILogger<AppSyncEventsClient>>();
            return new AppSyncEventsClient(appSyncClient, logger, eventApiId);
        });
        return services;
    }
}