openapi: 3.0.1
paths:
  # LzNotification
  '/{prefix}/lzNotificationsPage/list/subscriptionId/{subscriptionId}/dateTimeTicks/{dateTimeTicks}':
    get:
      operationId: LzNotificationsPageListSessionIdDateTimeTicks
      description: list LzNotifications for current subscriptionId from specified dateTime
      parameters:
      - name: subscriptionId
        in: path
        required: true 
        schema:
          type: string
      - name: dateTimeTicks
        in: path
        required: true 
        schema:
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzNotificationsPage'
        '403':
          description: Invalid permissions

  '/{prefix}/Notification':
    post:
      summary: Create a Notification record for testing 
      operationId: addNotificaiton
      x-lz-gencall: lzNotificationRepo.CreateAsync(callerInfo,body)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LzNotification'
      responses:
        '200':
          description: successful operation 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzNotification'

  '/{prefix}/lzSubscription/{id}':
    get:
      operationId: getLzSubscriptionById
      x-lz-gencall: lzSubscriptionRepo.ReadAsync(callerInfo,sessionId)   
      description: GetLzSubscription record 
      parameters:
      - name: sessionId
        in: path 
        required: true 
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzSubscription'
        '403':
          description: Invalid permissions

  '/{prefix}/lzSubscription':
    post:
      operationId: subscribe 
      description: subscribe to topics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LzSubscription'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzSubscription'
        '405':
          description: Invalid input
