openapi: 3.0.1
paths:
  # Test/Util
  '/{prefix}/publicTest':
    get:
      operationId: publicTest
      responses:
        '200':
          description: successful operation
          content:
            text/plain:
              schema:
                type: string

  '/{prefix}/pet/listPets':
    get:
      summary: List all pets 
      operationId: listPets 
      x-lz-gencall: petRepo.ListAsync(callerInfo) 
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid status value
          
  '/{prefix}/pet/findByStatus':
    get:
      summary: Finds Pets by status
      description: Multiple status values can be provided with comma separated strings
      operationId: findPetsByStatus
      # x-lz-gencall: petRepo.FindPetsByStatusAsync(callerInfo, petStatus)
      parameters:
      - name: petStatus
        in: query
        description: Status values that need to be considered for filter
        required: true
        explode: true
        schema:
          type: array
          items:
            $ref: '#/components/schemas/PetStatus'
          default: available
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid status value

  '/{prefix}/pet/{petId}':
    get:
      summary: Find pet by ID
      description: Returns a single pet
      operationId: getPetById
      x-lz-gencall: petRepo.ReadAsync(callerInfo, petId)
      parameters:
      - name: petId
        in: path
        description: ID of pet to return
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found

  '/{prefix}/pet/findByTags':
    get:
      summary: Finds Pets by tags
      description: >-
        Muliple tags can be provided with comma separated strings. Use\ \ tag1, tag2, tag3 for testing.
      operationId: findPetsByTags
      # x-lz-gencall: petRepo.FindPetsByTagsAsync(callerInfo, tags)
      parameters:
      - name: tags
        in: query
        description: Tags to filter by
        required: true
        explode: true
        schema:
          type: array
          items:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Pet'
        '400':
          description: Invalid tag value
  # Categories
  '/{prefix}/pet/categories':
    get:
      summary: Get all Pet Categories
      operationId: getPetCategories
      x-lz-gencall: categoryRepo.ListAsync(callerInfo)
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  # Tags
  '/{prefix}/pet/tags':
    get:
      summary: Get all Pet Tags
      operationId: getPetTags
      x-lz-gencall: tagRepo.ListAsync(callerInfo)
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
