// Generated by LazyMagic - modifications will be overwritten
using Microsoft.AspNetCore.Authentication.JwtBearer;
using LambdaFunc;

var builder = WebApplication.CreateBuilder(args);

// Add services to the container
builder.Services.AddControllers()
    .AddNewtonsoftJson();

// Add authentication
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme)
    .AddJwtBearer(options =>
    {
        // Configure JWT validation for Cognito
        // These will be set via environment variables
        var region = Environment.GetEnvironmentVariable("AWS_REGION");
        var userPoolId = Environment.GetEnvironmentVariable("COGNITO_USER_POOL_ID");

        if (!string.IsNullOrEmpty(region) && !string.IsNullOrEmpty(userPoolId))
        {
            options.Authority = $"https://cognito-idp.{region}.amazonaws.com/{userPoolId}";
            options.TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidateAudience = false,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true
            };
        }
    });

// Add AWS services
builder.Services.AddAWSService<Amazon.AppSync.IAmazonAppSync>();
builder.Services.AddAWSService<Amazon.BedrockRuntime.IAmazonBedrockRuntime>();

// Add CORS
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.SetIsOriginAllowed(origin =>
                  origin.StartsWith("https://") || origin.StartsWith("http://"))
              .WithHeaders(
                  "Authorization",
                  "lz-cognito-region",
                  "lz-cognito-userpool-id")
              .AllowAnyHeader()
              .WithMethods(
                  "GET",
                  "HEAD",
                  "PUT",
                  "OPTIONS",
                  "POST",
                  "DELETE")
              .WithExposedHeaders(
                  "Date",
                  "x-api-id",
                  "lz-cognito-region",
                  "lz-cognito-userpool-id")
              .SetPreflightMaxAge(TimeSpan.FromSeconds(600))
              .DisallowCredentials();
    });
});

// Add health checks
builder.Services.AddHealthChecks();

// Configure services (will be generated)
var startup = new Startup(builder.Configuration);
startup.ConfigureServices(builder.Services);

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

app.UseRouting();

app.UseCors();

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHealthChecks("/health");

app.Run();