// Generated by LazyMagic - modifications will be overwritten
// Host customization: Program is a partial class. Implement the partial hook
// methods declared at the bottom of this file in a hand-written Program.cs
// (which survives regeneration) to extend or replace the default behavior.
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.IdentityModel.Tokens;
using System.Text.RegularExpressions;

var builder = WebApplication.CreateBuilder(args);

// Hook: logging providers and configuration sources (e.g. tenant config)
ConfigureHostBuilder(builder);

// Add services to the container
builder.Services.AddControllers()
    .AddNewtonsoftJson();

builder.Services.AddHttpContextAccessor();

// Authentication: hook first; default LZ_AUTH_* Cognito discovery when not handled
var authHandled = false;
ConfigureCustomAuthentication(builder, ref authHandled);
if (!authHandled)
{
    // Discover and register authenticators dynamically
    var defaultRegion = Environment.GetEnvironmentVariable("AWS_REGION") ?? "us-east-1";
    var authenticators = DiscoverAuthenticators(defaultRegion);

    if (authenticators.Count == 0)
    {
        // Fallback to legacy single authenticator if no LZ_AUTH_* variables found
        var legacyUserPoolId = Environment.GetEnvironmentVariable("COGNITO_USER_POOL_ID");
        if (!string.IsNullOrEmpty(legacyUserPoolId))
        {
            authenticators["default"] = new AuthenticatorConfig
            {
                UserPoolId = legacyUserPoolId,
                Region = defaultRegion
            };
            Console.WriteLine("Using legacy COGNITO_USER_POOL_ID configuration");
        }
        else
        {
            throw new InvalidOperationException(
                "No authenticators configured. Set environment variables like: LZ_AUTH_TENANTAUTH_USERPOOLID");
        }
    }

    // Register each discovered authenticator as a named JWT Bearer scheme
    var authBuilder = builder.Services.AddAuthentication();

    foreach (var (authName, config) in authenticators)
    {
        var authority = $"https://cognito-idp.{config.Region}.amazonaws.com/{config.UserPoolId}";

        authBuilder.AddJwtBearer(authName, options =>
        {
            options.Authority = authority;
            options.TokenValidationParameters = new TokenValidationParameters
            {
                ValidateIssuer = true,
                ValidIssuer = authority,  // Explicitly set ValidIssuer
                ValidateAudience = false,
                ValidateLifetime = true,
                ValidateIssuerSigningKey = true
            };

            options.Events = new JwtBearerEvents
            {
                OnMessageReceived = context =>
                {
                    var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<Program>>();
                    logger.LogDebug("[{AuthName}] OnMessageReceived - Token present: {HasToken}",
                        authName,
                        !string.IsNullOrEmpty(context.Token));
                    return Task.CompletedTask;
                },

                OnAuthenticationFailed = context =>
                {
                    var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<Program>>();
                    logger.LogWarning("[{AuthName}] Authentication failed. Exception: {ExceptionType} - {Message}\nAuthority: {Authority}\nValidIssuer: {ValidIssuer}",
                        authName,
                        context.Exception?.GetType().Name,
                        context.Exception?.Message,
                        options.Authority,
                        options.TokenValidationParameters.ValidIssuer);

                    if (context.Exception?.InnerException != null)
                    {
                        logger.LogWarning("[{AuthName}] Inner exception: {InnerExceptionType} - {InnerMessage}",
                            authName,
                            context.Exception.InnerException.GetType().Name,
                            context.Exception.InnerException.Message);
                    }

                    return Task.CompletedTask;
                },

                OnTokenValidated = context =>
                {
                    var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<Program>>();

                    // Log successful validation details
                    var issuer = context.Principal?.Claims.FirstOrDefault(c => c.Type == "iss")?.Value;
                    var subject = context.Principal?.Claims.FirstOrDefault(c => c.Type == "sub")?.Value;
                    var expClaim = context.Principal?.Claims.FirstOrDefault(c => c.Type == "exp")?.Value;

                    logger.LogInformation("[{AuthName}] Token validated successfully. Issuer: {Issuer}, Subject: {Subject}, Exp: {Exp}",
                        authName,
                        issuer,
                        subject,
                        expClaim);

                    // Add lz-authname header when this scheme succeeds
                    if (!context.HttpContext.Request.Headers.ContainsKey("lz-authname"))
                    {
                        context.HttpContext.Request.Headers["lz-authname"] = authName;
                        logger.LogDebug("[{AuthName}] Added lz-authname header to request", authName);
                    }

                    return Task.CompletedTask;
                },

                OnChallenge = context =>
                {
                    var logger = context.HttpContext.RequestServices.GetRequiredService<ILogger<Program>>();
                    logger.LogWarning("[{AuthName}] OnChallenge - Error: {Error}, ErrorDescription: {ErrorDescription}",
                        authName,
                        context.Error,
                        context.ErrorDescription);
                    return Task.CompletedTask;
                }
            };
        });

        Console.WriteLine($"Registered authenticator: {authName} (Region: {config.Region}, Pool: {config.UserPoolId}, Authority: {authority})");
    }

    // Store authenticator names for middleware
    builder.Services.AddSingleton(authenticators.Keys.ToList());
}

// CORS: hook first; default policy when not handled
var corsHandled = false;
ConfigureCustomCors(builder, ref corsHandled);
if (!corsHandled)
{
    builder.Services.AddCors(options =>
    {
        options.AddDefaultPolicy(policy =>
        {
            policy.SetIsOriginAllowed(origin =>
                      origin.StartsWith("https://") || origin.StartsWith("http://"))
                  .WithHeaders(
                      "Authorization",
                      "lz-cognito-region",
                      "lz-cognito-userpool-id",
                      "lz-authname")
                  .AllowAnyHeader()
                  .WithMethods(
                      "GET",
                      "HEAD",
                      "PUT",
                      "OPTIONS",
                      "PATCH",
                      "POST",
                      "DELETE")
                  .WithExposedHeaders(
                      "Date",
                      "x-api-id",
                      "lz-cognito-region",
                      "lz-cognito-userpool-id",
                      "lz-authname")
                  .SetPreflightMaxAge(TimeSpan.FromSeconds(600))
                  .DisallowCredentials();
        });
    });
}

// Add health checks
builder.Services.AddHealthChecks();

// Configure services (will be generated)
var startup = new Startup(builder.Configuration);
startup.ConfigureServices(builder.Services);

var app = builder.Build();

// Configure the HTTP request pipeline
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}

// Hook: middleware that must run before routing (request logging, path rewriting, ...)
ConfigurePipelinePreRouting(app);

app.UseRouting();

app.UseCors();

// Multi-scheme authentication middleware: hook first; default lz-authname
// header-based middleware when not handled
var authMiddlewareHandled = false;
ConfigureAuthenticationMiddleware(app, ref authMiddlewareHandled);
if (!authMiddlewareHandled)
{
    app.Use(async (context, next) =>
    {
        var registeredAuthNames = context.RequestServices.GetService<List<string>>() ?? new List<string>();
        var logger = context.RequestServices.GetRequiredService<ILogger<Program>>();
        var authNameHeader = context.Request.Headers["lz-authname"].FirstOrDefault();

        if (!string.IsNullOrEmpty(authNameHeader))
        {
            // Specific authentication scheme requested
            if (registeredAuthNames.Contains(authNameHeader, StringComparer.OrdinalIgnoreCase))
            {
                logger.LogDebug("Using authentication scheme from header: {AuthName}", authNameHeader);
                var result = await context.AuthenticateAsync(authNameHeader);
                if (result.Succeeded)
                {
                    context.User = result.Principal;
                }
                else
                {
                    logger.LogWarning("Authentication failed for scheme: {AuthName}", authNameHeader);
                }
            }
            else
            {
                logger.LogWarning("Invalid lz-authname specified: {AuthName}", authNameHeader);
                context.Response.StatusCode = 400;
                await context.Response.WriteAsJsonAsync(new
                {
                    error = "Invalid lz-authname",
                    value = authNameHeader,
                    validValues = registeredAuthNames
                });
                return;
            }
        }
        else
        {
            // No lz-authname header - try each registered authenticator until one succeeds
            logger.LogDebug("No lz-authname header found, trying all registered authenticators");

            foreach (var authName in registeredAuthNames)
            {
                var result = await context.AuthenticateAsync(authName);
                if (result.Succeeded)
                {
                    logger.LogInformation("Successfully authenticated with scheme: {AuthName}", authName);
                    context.User = result.Principal;
                    context.Request.Headers["lz-authname"] = authName;
                    break;
                }
                else
                {
                    logger.LogDebug("Authentication failed with scheme {AuthName}: {Failure}",
                        authName, result.Failure?.Message);
                }
            }
        }

        await next();
    });
}

app.UseAuthentication();
app.UseAuthorization();

app.MapControllers();
app.MapHealthChecks("/health");

app.Run();

// ===== HELPER FUNCTIONS =====

/// <summary>
/// Discovers authenticators from environment variables matching pattern: LZ_AUTH_{NAME}_USERPOOLID
/// Optional per-authenticator region override: LZ_AUTH_{NAME}_REGION
/// </summary>
static Dictionary<string, AuthenticatorConfig> DiscoverAuthenticators(string defaultRegion)
{
    var authenticators = new Dictionary<string, AuthenticatorConfig>(StringComparer.OrdinalIgnoreCase);
    var envVars = Environment.GetEnvironmentVariables();
    var regex = new Regex(@"^LZ_AUTH_(?<name>[A-Z0-9_]+)_USERPOOLID$", RegexOptions.IgnoreCase);

    foreach (var key in envVars.Keys)
    {
        var match = regex.Match(key.ToString() ?? string.Empty);
        if (match.Success)
        {
            var authName = match.Groups["name"].Value.ToLowerInvariant();
            var userPoolId = envVars[key]?.ToString();

            if (string.IsNullOrEmpty(userPoolId))
            {
                Console.WriteLine($"Warning: Empty UserPoolId for authenticator: {authName}");
                continue;
            }

            // Check for optional region override
            var regionKey = $"LZ_AUTH_{authName.ToUpperInvariant()}_REGION";
            var region = Environment.GetEnvironmentVariable(regionKey) ?? defaultRegion;

            authenticators[authName] = new AuthenticatorConfig
            {
                UserPoolId = userPoolId,
                Region = region
            };
        }
    }

    return authenticators;
}

// ===== HOST EXTENSION POINTS =====
// Implement any of these partial methods in a hand-written Program.cs in the
// target project (hand-written files survive regeneration). Hooks with a
// 'ref bool handled' parameter replace the corresponding default block when
// the implementation sets handled = true.
public partial class Program
{
    /// <summary>
    /// Called immediately after WebApplication.CreateBuilder. Add configuration
    /// sources (e.g. tenant config from SSM), logging providers, and host-level
    /// service registrations here.
    /// </summary>
    static partial void ConfigureHostBuilder(WebApplicationBuilder builder);

    /// <summary>
    /// Set handled = true to replace the default LZ_AUTH_* Cognito JWT discovery
    /// with a custom authentication registration (e.g. config-driven issuers).
    /// </summary>
    static partial void ConfigureCustomAuthentication(WebApplicationBuilder builder, ref bool handled);

    /// <summary>
    /// Set handled = true to replace the default CORS policy.
    /// </summary>
    static partial void ConfigureCustomCors(WebApplicationBuilder builder, ref bool handled);

    /// <summary>
    /// Middleware installed after the developer exception page and before
    /// UseRouting (e.g. request logging, path rewriting).
    /// </summary>
    static partial void ConfigurePipelinePreRouting(WebApplication app);

    /// <summary>
    /// Set handled = true to replace the default lz-authname multi-scheme
    /// authentication middleware.
    /// </summary>
    static partial void ConfigureAuthenticationMiddleware(WebApplication app, ref bool handled);
}
