// Generated by LazyMagic - modifications will be overwritten
// Create a separate Startup.cs file for project specific startup code.
public partial class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public static IConfiguration Configuration { get; private set; } = null!;

    // This method gets called to configure services. ConfigureSvcs will be generated.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddDefaultAWSOptions(Configuration.GetAWSOptions());

        // Hook for host-specific service registrations (before modules are registered)
        ConfigureHostServices(services);

        ConfigureSvcs(services);
        services.AddControllers().AddNewtonsoftJson();
    }

    /// <summary>
    /// Override in the host's Startup.cs to register implementation-specific services
    /// (e.g. secrets providers, integration registries, store services).
    /// Called before modules are registered, allowing modules to depend on interfaces
    /// that are implemented by services registered here.
    /// </summary>
    partial void ConfigureHostServices(IServiceCollection services);
}
