
// Generated by LazyMagic - modifications will be overwritten
namespace LambdaFunc;
public partial class Startup
{
    public void ConfigureSvcs(IServiceCollection services)
    {
        services.AddChatModule();
		services.AddSingleton<SessionManager>();
		services.AddSingleton<AppSyncEventPublisher>();
		services.AddScoped<BedrockChat>();
		services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer();
		services.ConfigureCognitoAuthentication();
    }
}
