<Project>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Amazon.AspNetCore.Identity.Cognito" />
    <PackageReference Include="AWSSDK.AppSync" />
    <PackageReference Include="AWSSDK.BedrockRuntime" />
    <PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../Modules/ChatModule/ChatModule.csproj" />
  </ItemGroup>
</Project>