//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using ChatModule;

namespace ChatApi
{
    public partial interface IChatApi : IChatModuleClient
    {
        // All methods inherited from module client interfaces
    }
}