
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace ConsumerSchemaRepo;
public partial interface IPreferencesRepo : IDocumentRepo<Preferences> {}
public partial class PreferencesRepo : DYDBRepository<Preferences>, IPreferencesRepo
{
    public PreferencesRepo(IAmazonDynamoDB client) : base(client) {}

    // From the Preferences schema's x-lz-tablelevel and x-lz-tablekind; LazyMagic's defaults when absent.
    protected override TableLevel TableLevel => TableLevel.Default;
    protected override TableKind TableKind => TableKind.Lsi;
}
