openapi: 3.0.1
paths:
  /Notification:
    post:
      summary: Create a Notification record for testing
      operationId: addNotificaiton
      x-lz-gencall: lzNotificationRepo.CreateAsync(callerInfo,body)
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LzNotification'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzNotification'
  /lzSubscription:
    post:
      operationId: subscribe
      description: subscribe to topics
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LzSubscription'
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzSubscription'
        405:
          description: Invalid input
  '/lzNotificationsPage/list/subscriptionId/{subscriptionId}/dateTimeTicks/{dateTimeTicks}':
    get:
      operationId: LzNotificationsPageListSessionIdDateTimeTicks
      description: list LzNotifications for current subscriptionId from specified dateTime
      parameters:
      - name: subscriptionId
        in: path
        required: true
        schema:
          type: string
      - name: dateTimeTicks
        in: path
        required: true
        schema:
          type: integer
          format: int64
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzNotificationsPage'
        403:
          description: Invalid permissions
  '/lzSubscription/{id}':
    get:
      operationId: getLzSubscriptionById
      x-lz-gencall: lzSubscriptionRepo.ReadAsync(callerInfo,sessionId)
      description: GetLzSubscription record
      parameters:
      - name: sessionId
        in: path
        required: true
        schema:
          type: string
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LzSubscription'
        403:
          description: Invalid permissions
components:
  schemas:
    LzNotification:
      type: object
      required:
      - id
      - topicId
      - userId
      - payloadType
      - payloadAction
      properties:
        id:
          type: string
        topics:
          type: string
          nullable: true
        userId:
          type: string
          nullable: true
        payloadParentId:
          type: string
          nullable: true
        payloadId:
          type: string
          nullable: true
        payloadType:
          type: string
          nullable: true
        payload:
          type: string
          nullable: true
        payloadAction:
          type: string
          nullable: true
        sessionId:
          type: string
          nullable: true
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
      x-lz-hasrepo: true
      x-lz-genschemaclass: false
    LzNotificationsPage:
      type: object
      properties:
        id:
          type: string
        LzNotifications:
          type: array
          items:
            $ref: '#/components/schemas/LzNotification'
        more:
          type: boolean
      x-lz-genschemaclass: false
    LzSubscription:
      type: object
      properties:
        id:
          type: string
          description: subscriptionId
        connectionId:
          type: string
          description: web socket connectionId
        userId:
          type: string
          description: lzUserId
          nullable: true
        topicIds:
          type: array
          items:
            type: string
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
      x-lz-hasrepo: true
      x-lz-genschemaclass: false
    Preferences:
      type: object
      properties:
        id:
          type: string
        theme:
          type: string
          enum:
          - light
          - dark
        locale:
          type: string
          enum:
          - en
          - fr
          - es
        petStatus:
          description: pet status in the store
          $ref: '#/components/schemas/PetStatus'
        pets:
          type: array
          items:
            $ref: '#/components/schemas/Pet'
        pet:
          $ref: '#/components/schemas/Pet'
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      x-lz-genrepo: true
    Tag:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      x-lz-genrepo: true
    Pet:
      type: object
      required:
      - name
      - photoUrls
      properties:
        id:
          type: string
        category:
          type: string
        name:
          type: string
          example: Dog
        photoUrls:
          type: array
          items:
            type: string
        tags:
          type: array
          items:
            type: string
        petStatus:
          description: pet status in the store
          default: available
          $ref: '#/components/schemas/PetStatus'
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
      x-lz-genrepo: true
    PetStatus:
      type: string
      description: pet status in the store
      enum:
      - available
      - pending
      - sold
    Order:
      type: object
      properties:
        id:
          type: string
        userId:
          type: string
          description: Cognito Identity Id of clerk entering order
        petId:
          type: integer
          format: int64
        quantity:
          type: integer
          format: int32
        shipDate:
          type: string
          format: date-time
        orderStatus:
          title: orderStatus
          description: Order Status
          $ref: '#/components/schemas/OrderStatus'
        complete:
          type: boolean
          default: false
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
      x-lz-genrepo: true
    OrderStatus:
      type: string
      description: Order Status
      enum:
      - placed
      - approved
      - delivered
    User:
      type: object
      properties:
        id:
          type: string
        login:
          type: string
          nullable: true
        name:
          type: string
        email:
          type: string
        phone:
          type: string
          nullable: true
        employee:
          type: boolean
        admin:
          type: boolean
        createUtcTick:
          type: integer
          format: int64
        updateUtcTick:
          type: integer
          format: int64
      x-lz-genrepo: true
    Bada:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      x-lz-genrepo: true
...
