//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using PublicModule;

namespace PublicApi
{
    public partial interface IPublicApi : IPublicModuleClient
    {
        // All methods inherited from module client interfaces
    }
}