
//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
//     Implement another class for registrations not directly generated by LazyMagic.
// </auto-generated>
//----------------------
namespace ChatModule
{
    public static partial class ChatModuleRegistrations 
    {
        public static IServiceCollection AddChatModule(this IServiceCollection services) 
        {
            services.TryAddSingleton<IChatModuleAuthorization, ChatModuleAuthorization>();
            services.TryAddSingleton<IChatModuleController, ChatModuleController>();
            services.AddChatSchemaRepo();
            CustomConfigurations(services);
            return services;            
        }
        static partial void CustomConfigurations(IServiceCollection services);
    }
}
