// NSWAG code refactored by LazyMagic.
// We use NSWAG to generate a baseclass, partial class and interface. 
// I{ModuleName}Controller.g.cs - defines a partial interface
// {ModuleName}ControllerBase.g.cs - defines the base class
// {ModuleName}Controller.g.cs - defines a partial class that inherits the base class
// To add or override class behavior, create a new partial class file
// {projectName}Controller.cs - overrides methods in the base class
// Dependency Injection system.
// Note: We also generate some helper classes 
// {ModuleName}Authorization.g.cs - Partial class for Authorization system
// {ModuleName}Registration.g.cs - Registers classes with the DI system
//
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace ChatModule
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract partial class ChatModuleControllerBase : Controller, IChatModuleController
    {

        /// <summary>
        /// Create new chat
        /// </summary>
        /// <remarks>
        /// Creates a new chat session
        /// </remarks>
        /// <returns>Chat created successfully</returns>
        [HttpPost, Route("ChatModule/chat")]
        public virtual async Task<ActionResult<Chat>> ChatModuleAddChatAsync([FromBody] Chat body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.CreateChatAsync(callerInfo, body);
        }
        /// <summary>
        /// List chats
        /// </summary>
        /// <remarks>
        /// Lists all chats for the authenticated user
        /// </remarks>
        /// <returns>Chats retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat")]
        public virtual async Task<ActionResult<System.Collections.Generic.ICollection<Chat>>> ChatModuleListChatsAsync()
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.ListChatsAsync(callerInfo);
        }
        /// <summary>
        /// Update chat
        /// </summary>
        /// <remarks>
        /// Updates an existing chat
        /// </remarks>
        /// <returns>Chat updated successfully</returns>
        [HttpPut, Route("ChatModule/chat")]
        public virtual async Task<ActionResult<Chat>> ChatModuleUpdateChatAsync([FromBody] Chat body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.UpdateChatAsync(callerInfo, body);
        }
        /// <summary>
        /// Health check endpoint
        /// </summary>
        /// <remarks>
        /// Health check endpoint for service monitoring
        /// </remarks>
        /// <returns>Service is healthy</returns>
        [HttpGet, Route("ChatModule/health")]
        public virtual async Task<ActionResult<HealthCheckResponse>> ChatModuleHealthCheckAsync()
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await HealthService.CheckAsync(callerInfo);
        }
        /// <summary>
        /// Get chat by ID
        /// </summary>
        /// <remarks>
        /// Retrieves a chat by its ID
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Chat retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat/{chatId}")]
        public virtual async Task<ActionResult<Chat>> ChatModuleGetChatByIdAsync(string chatId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.GetChatAsync(callerInfo, chatId);
        }
        /// <summary>
        /// Delete chat
        /// </summary>
        /// <remarks>
        /// Deletes a chat and cleans up resources
        /// </remarks>
        /// <param name="chatId">ID of the chat to delete</param>
        /// <returns>Chat deleted successfully</returns>
        [HttpDelete, Route("ChatModule/chat/{chatId}")]
        public virtual async Task<IActionResult> ChatModuleDeleteChatAsync(string chatId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.DeleteChatAsync(callerInfo, chatId);
        }
        /// <summary>
        /// Send message to chat
        /// </summary>
        /// <remarks>
        /// Sends a new message to an existing chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Message sent successfully</returns>
        [HttpPost, Route("ChatModule/chat/{chatId}/messages")]
        public virtual async Task<ActionResult<ChatMessage>> ChatModuleAddChatMessageAsync(string chatId, [FromBody] ChatMessage body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.SendMessageAsync(callerInfo, chatId, body);
        }
        /// <summary>
        /// Get chat messages
        /// </summary>
        /// <remarks>
        /// Retrieves message history for a chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of messages per page</param>
        /// <returns>Messages retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat/{chatId}/messages")]
        public virtual async Task<ActionResult<System.Collections.Generic.ICollection<ChatMessage>>> ChatModuleGetChatMessagesAsync(string chatId, [FromQuery] int? page = null, [FromQuery] int? limit = null)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatManagerService.GetMessagesAsync(callerInfo, chatId, page, limit);
        }
		public IChatModuleAuthorization ChatModuleAuthorization { get; set; }
		public IChatRepo ChatRepo { get; set; }
		public IChatContextRepo ChatContextRepo { get; set; }
		protected virtual void Init() { }
    }


}
