// NSWAG code refactored by LazyMagic.
// We use NSWAG to generate a baseclass, partial class and interface. 
// I{ModuleName}Controller.g.cs - defines a partial interface
// {ModuleName}ControllerBase.g.cs - defines the base class
// {ModuleName}Controller.g.cs - defines a partial class that inherits the base class
// To add or override class behavior, create a new partial class file
// {projectName}Controller.cs - overrides methods in the base class
// Dependency Injection system.
// Note: We also generate some helper classes 
// {ModuleName}Authorization.g.cs - Partial class for Authorization system
// {ModuleName}Registration.g.cs - Registers classes with the DI system
//
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace ChatModule
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class ChatModuleControllerBase : Controller, IChatModuleController
    {

        /// <summary>
        /// Create new chat session
        /// </summary>
        /// <remarks>
        /// Creates a new chat session and starts processing the initial message
        /// </remarks>
        /// <returns>Session created successfully</returns>
        [HttpPost, Route("ChatModule/session/create")]
        public virtual async Task<ActionResult<CreateSessionResponse>> ChatModuleCreateSessionAsync([FromBody] CreateSessionRequest body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await SessionManager.CreateSessionAsync(callerInfo, body);
        }
        /// <summary>
        /// Health check endpoint
        /// </summary>
        /// <remarks>
        /// Health check endpoint for App Runner service monitoring
        /// </remarks>
        /// <returns>Service is healthy</returns>
        [HttpGet, Route("ChatModule/health")]
        public virtual async Task<ActionResult<HealthCheckResponse>> ChatModuleHealthCheckAsync()
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await HealthService.CheckAsync(callerInfo);
        }
        /// <summary>
        /// Send message to existing session
        /// </summary>
        /// <remarks>
        /// Sends a message to an existing chat session
        /// </remarks>
        /// <param name="sessionId">ID of the chat session</param>
        /// <returns>Message sent successfully</returns>
        [HttpPost, Route("ChatModule/session/{sessionId}/message")]
        public virtual async Task<ActionResult<SendMessageResponse>> ChatModuleSendMessageAsync(string sessionId, [FromBody] SendMessageRequest body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await SessionManager.SendMessageAsync(callerInfo, sessionId, body);
        }
        /// <summary>
        /// Get session status
        /// </summary>
        /// <remarks>
        /// Retrieves the current status and information about a chat session
        /// </remarks>
        /// <param name="sessionId">ID of the chat session</param>
        /// <returns>Session status retrieved successfully</returns>
        [HttpGet, Route("ChatModule/session/{sessionId}/status")]
        public virtual async Task<ActionResult<GetSessionStatusResponse>> ChatModuleGetSessionStatusAsync(string sessionId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await SessionManager.GetSessionStatusAsync(callerInfo, sessionId);
        }
        /// <summary>
        /// Close chat session
        /// </summary>
        /// <remarks>
        /// Closes an active chat session and cleans up resources
        /// </remarks>
        /// <param name="sessionId">ID of the chat session to close</param>
        /// <returns>Session closed successfully</returns>
        [HttpDelete, Route("ChatModule/session/{sessionId}")]
        public virtual async Task<IActionResult> ChatModuleCloseSessionAsync(string sessionId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await SessionManager.CloseSessionAsync(callerInfo, sessionId);
        }
        /// <summary>
        /// Get session message history
        /// </summary>
        /// <remarks>
        /// Retrieves the message history for a chat session
        /// </remarks>
        /// <param name="sessionId">ID of the chat session</param>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of messages per page</param>
        /// <returns>Message history retrieved successfully</returns>
        [HttpGet, Route("ChatModule/session/{sessionId}/messages")]
        public virtual async Task<ActionResult<SessionMessagesResponse>> ChatModuleGetSessionMessagesAsync(string sessionId, [FromQuery] int? page = null, [FromQuery] int? limit = null)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await SessionManager.GetSessionMessagesAsync(callerInfo, sessionId, page, limit);
        }
		public IChatModuleAuthorization ChatModuleAuthorization { get; set; }
		public ICategoryRepo CategoryRepo { get; set; }
		public ITagRepo TagRepo { get; set; }
		public IPetRepo PetRepo { get; set; }
		public IOrderRepo OrderRepo { get; set; }
		protected virtual void Init() { }
    }


}
