// NSWAG code refactored by LazyMagic.
// We use NSWAG to generate a baseclass, partial class and interface. 
// I{ModuleName}Controller.g.cs - defines a partial interface
// {ModuleName}ControllerBase.g.cs - defines the base class
// {ModuleName}Controller.g.cs - defines a partial class that inherits the base class
// To add or override class behavior, create a new partial class file
// {projectName}Controller.cs - overrides methods in the base class
// Dependency Injection system.
// Note: We also generate some helper classes 
// {ModuleName}Authorization.g.cs - Partial class for Authorization system
// {ModuleName}Registration.g.cs - Registers classes with the DI system
//
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace ChatModule
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class ChatModuleControllerBase : Controller, IChatModuleController
    {

        /// <summary>
        /// Create new chat
        /// </summary>
        /// <remarks>
        /// Creates a new chat and starts processing the initial message
        /// </remarks>
        /// <returns>Chat created successfully</returns>
        [HttpPost, Route("ChatModule/chat/create")]
        public virtual async Task<ActionResult<CreateChatResponse>> ChatModuleCreateChatAsync([FromBody] CreateChatRequest body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.CreateChatAsync(callerInfo, body);
        }
        /// <summary>
        /// List chats
        /// </summary>
        /// <remarks>
        /// Lists all chats for the authenticated user with pagination
        /// </remarks>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of chats per page</param>
        /// <param name="status">Filter by chat status</param>
        /// <returns>Chats retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat")]
        public virtual async Task<ActionResult<ListChatsResponse>> ChatModuleListChatsAsync([FromQuery] int? page = null, [FromQuery] int? limit = null, [FromQuery] ChatStatus? status = null)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.ListChatsAsync(callerInfo, page, limit, status);
        }
        /// <summary>
        /// Health check endpoint
        /// </summary>
        /// <remarks>
        /// Health check endpoint for App Runner service monitoring
        /// </remarks>
        /// <returns>Service is healthy</returns>
        [HttpGet, Route("ChatModule/health")]
        public virtual async Task<ActionResult<HealthCheckResponse>> ChatModuleHealthCheckAsync()
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await HealthService.CheckAsync(callerInfo);
        }
        /// <summary>
        /// Send message to existing chat
        /// </summary>
        /// <remarks>
        /// Sends a message to an existing chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Message sent successfully</returns>
        [HttpPost, Route("ChatModule/chat/{chatId}/message")]
        public virtual async Task<ActionResult<SendMessageResponse>> ChatModuleSendMessageAsync(string chatId, [FromBody] SendMessageRequest body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.SendMessageAsync(callerInfo, chatId, body);
        }
        /// <summary>
        /// Get chat status
        /// </summary>
        /// <remarks>
        /// Retrieves the current status and information about a chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Chat status retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat/{chatId}/status")]
        public virtual async Task<ActionResult<GetChatStatusResponse>> ChatModuleGetChatStatusAsync(string chatId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.GetChatStatusAsync(callerInfo, chatId);
        }
        /// <summary>
        /// Get chat by ID
        /// </summary>
        /// <remarks>
        /// Retrieves a chat by its ID from persistent storage
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Chat retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat/{chatId}")]
        public virtual async Task<ActionResult<GetChatResponse>> ChatModuleGetChatAsync(string chatId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.GetChatAsync(callerInfo, chatId);
        }
        /// <summary>
        /// Update chat
        /// </summary>
        /// <remarks>
        /// Updates chat metadata and status in persistent storage
        /// </remarks>
        /// <param name="chatId">ID of the chat to update</param>
        /// <returns>Chat updated successfully</returns>
        [HttpPut, Route("ChatModule/chat/{chatId}")]
        public virtual async Task<ActionResult<UpdateChatResponse>> ChatModuleUpdateChatAsync(string chatId, [FromBody] UpdateChatRequest body)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.UpdateChatAsync(callerInfo, chatId, body);
        }
        /// <summary>
        /// Close chat
        /// </summary>
        /// <remarks>
        /// Closes an active chat and cleans up resources
        /// </remarks>
        /// <param name="chatId">ID of the chat to close</param>
        /// <returns>Chat closed successfully</returns>
        [HttpDelete, Route("ChatModule/chat/{chatId}")]
        public virtual async Task<IActionResult> ChatModuleCloseChatAsync(string chatId)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.CloseChatAsync(callerInfo, chatId);
        }
        /// <summary>
        /// Get chat message history
        /// </summary>
        /// <remarks>
        /// Retrieves the message history for a chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of messages per page</param>
        /// <returns>Message history retrieved successfully</returns>
        [HttpGet, Route("ChatModule/chat/{chatId}/messages")]
        public virtual async Task<ActionResult<ChatMessagesResponse>> ChatModuleGetChatMessagesAsync(string chatId, [FromQuery] int? page = null, [FromQuery] int? limit = null)
        {
            var callerInfo = await ChatModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await ChatRepo.GetChatMessagesAsync(callerInfo, chatId, page, limit);
        }
		public IChatModuleAuthorization ChatModuleAuthorization { get; set; }
		public IChatRepo ChatRepo { get; set; }
		public IChatMessagesRepo ChatMessagesRepo { get; set; }
		protected virtual void Init() { }
    }


}
