
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace PublicSchemaRepo;
public partial interface IBadaRepo : IDocumentRepo<Bada> {}
public partial class BadaRepo : DYDBRepository<Bada>, IBadaRepo
{
    public BadaRepo(IAmazonDynamoDB client) : base(client) {}

    // From the Bada schema's x-lz-tablelevel and x-lz-tablekind; LazyMagic's defaults when absent.
    protected override TableLevel TableLevel => TableLevel.Default;
    protected override TableKind TableKind => TableKind.Lsi;
}
