
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace PublicSchemaRepo;
public partial interface IFingerprintRepo : IDocumentRepo<Fingerprint> {}
public partial class FingerprintRepo : DYDBRepository<Fingerprint>, IFingerprintRepo
{
    public FingerprintRepo(IAmazonDynamoDB client) : base(client) {}
}
