
// Generated by LazyMagic - modifications will be overwritten
namespace LambdaFunc;
public partial class Startup
{
    public void ConfigureSvcs(IServiceCollection services)
    {
        services.AddChatModule();
		services.AddPublicModule();
		services.AddConsumerModule();
		services.AddStoreModule();
		services.AddAdminModule();
    }
}
