AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: | 
  This stack creates the S3 bucket a web application

Parameters:
  SystemKeyParameter:
    Description: "System Name"
    Type: String
  AppNameParameter:
    Description: "App Name"
    Type: String
  GuidParameter:
    Description: "Guid"
    Type: String


Resources:
  AppBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${SystemKeyParameter}---webapp-${AppNameParameter}-${GuidParameter}'

  AppBucketPolicy:
    Type: AWS::S3::BucketPolicy
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Bucket: !Ref AppBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AppBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref AWS::AccountId
Outputs:
  AppBucket:
    Description: The WebApp Bucket
    Value: !Ref AppBucket
