AWSTemplateFormatVersion: '2010-09-09'
Transform: 
  - 'AWS::Serverless-2016-10-31'
  - 'AWS::LanguageExtensions'
Description: | 
  This stack is used to create tenancy assets
    This includes
      Tenancy Assets bucket
      Tenancy CDNLog Bucket policy
      Tenancy DynamoDb table (note that tables are used like separate databases in DynamoDB)

# Note that this template doesn't allow the deletion of the assets bucket, CDN log bucket, and DynamoDB table
# Also, if the reosurces exist, they are not updated or replaced

Parameters:

  SystemKeyParameter:
    Description: "System Name"
    Type: String
    MinLength: 1

  TenantKeyParameter:
    Description: "Tenant Key. No spaces. Lower case."
    Type: String
    MinLength: 1

  SubtenantKeyParameter:
    Description: "Optional SubTenant Key. No spaces. Lower case."
    Type: String
    Default: "" 

  # GuidParameter is usually the SystemSuffix in the serviceconfig.yaml file
  GuidParameter:
    Description: "GuidParameter"
    Type: String

  CreateAssetsBucketParameter:
    Description: "Create Assets Bucket"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

  CreateTenantDBParameter:
    Description: "Create Tenant DB"
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"

Conditions:
  IsTenant: !Equals [!Ref SubtenantKeyParameter, ""]
  CreateAssetsBucket: !Equals [!Ref CreateAssetsBucketParameter, "true"]
  CreateTenantDB: !Equals [!Ref CreateTenantDBParameter, "true"]

Resources:
  AssetsBucket:
    Type: AWS::S3::Bucket
    Condition: CreateAssetsBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub "${SystemKeyParameter}-${TenantKeyParameter}-${SubtenantKeyParameter}-assets-${GuidParameter}"

  AssetsBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: CreateAssetsBucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      Bucket: !Ref AssetsBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontRead
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 
              - s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${AssetsBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceAccount: !Ref AWS::AccountId

  # The Tenancy DynamoDb table is used like a separate database in DynamoDB
  # See the LazyMagic documentation for more information on how to use this table
  # with the LazyMagic.DynamoDBRepo library/package.
  TenantDB:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Condition: CreateTenantDB
    Properties:
      TableName: !Sub "${SystemKeyParameter}-${TenantKeyParameter}-${SubtenantKeyParameter}"
      TimeToLiveSpecification:
        AttributeName: TTL
        Enabled: true
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: S
      - AttributeName: SK1
        AttributeType: S
      - AttributeName: SK2
        AttributeType: S
      - AttributeName: SK3
        AttributeType: S
      - AttributeName: SK4
        AttributeType: S
      - AttributeName: SK5
        AttributeType: S
      - AttributeName: GSI1PK
        AttributeType: S
      - AttributeName: GSI1SK
        AttributeType: S
      BillingMode: PAY_PER_REQUEST
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: PK-SK1-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK1
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK2-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK2
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK3-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK3
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK4-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK4
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      - IndexName: PK-SK5-Index
        KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK5
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE
      GlobalSecondaryIndexes:
      - IndexName: GSI1
        KeySchema:
        - AttributeName: GSI1PK
          KeyType: HASH
        - AttributeName: GSI1SK
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Status
          - UpdateUtcTick
          - CreateUtcTick
          - General
          ProjectionType: INCLUDE

Outputs:
  AssetsBucketName:
    Description: "Config Bucket Name"
    Value: !If
    - CreateAssetsBucket
    - !Ref AssetsBucket
    - !Sub "${SystemKeyParameter}$-{TenantKeyParameter}$-{SubtenantKeyParameter}-assets-${GuidParameter}"
 
  TenantDBName:
    Description: "Tenant DB Name"
    Value: !If
    - CreateTenantDB
    - !Ref TenantDB
    - !Sub "${SystemKeyParameter}$-${TenantKeyParameter}-${SubtenantKeyParameter}"
