<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<IsPackable>false</IsPackable>
		<IsTestProject>true</IsTestProject>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector" />
		<PackageReference Include="Microsoft.NET.Test.Sdk" />
		<PackageReference Include="xunit" />
		<PackageReference Include="xunit.runner.visualstudio" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" />
		<PackageReference Include="Microsoft.Extensions.Configuration" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Json" />
		<PackageReference Include="AWSSDK.DynamoDBv2" />
		<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" />
		<PackageReference Include="AWSSDK.SecurityToken" />
		<PackageReference Include="AWSSDK.SSO" />
		<PackageReference Include="AWSSDK.SSOOIDC" />
		<PackageReference Include="YamlDotNet" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Modules\ChatModule\ChatModule.csproj" />
		<ProjectReference Include="..\Schemas\ChatSchema\ChatSchema.csproj" />
		<ProjectReference Include="..\Schemas\ChatSchemaRepo\ChatSchemaRepo.csproj" />
	</ItemGroup>

</Project>
