//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using ChatModule;
using PublicModule;
using ConsumerModule;
using StoreModule;

namespace TenantApi
{
    public partial interface ITenantApi : IChatModuleClient, IPublicModuleClient, IConsumerModuleClient, IStoreModuleClient
    {
        // All methods inherited from module client interfaces
    }
}