
//----------------------
// <auto-generated>
//     Generated using the NSwag library. 
//     Refactored into the schema project by LazyMagic.
//     Do not modify, your changes will be overwritten.
//     This is a partial class so you can extend the class in a separate file.
//     Only files with *.g.* extensions will be overwritten.
// </auto-generated>
//----------------------

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'.Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ..."
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"

namespace ChatSchema
{
    using System = global::System;
    
    /// <summary>
    /// Type of chat event
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]
    public enum ChatEventType
    {

        [System.Runtime.Serialization.EnumMember(Value = @"chat_created")]
        Chat_created = 0,

        [System.Runtime.Serialization.EnumMember(Value = @"chat_status_changed")]
        Chat_status_changed = 1,

        [System.Runtime.Serialization.EnumMember(Value = @"message_received")]
        Message_received = 2,

        [System.Runtime.Serialization.EnumMember(Value = @"message_processing")]
        Message_processing = 3,

        [System.Runtime.Serialization.EnumMember(Value = @"message_streaming")]
        Message_streaming = 4,

        [System.Runtime.Serialization.EnumMember(Value = @"message_completed")]
        Message_completed = 5,

        [System.Runtime.Serialization.EnumMember(Value = @"chat_closed")]
        Chat_closed = 6,

        [System.Runtime.Serialization.EnumMember(Value = @"error_occurred")]
        Error_occurred = 7,

    }

}
#pragma warning restore 1591
#pragma warning restore 1573
#pragma warning restore  472
#pragma warning restore  114
#pragma warning restore  108
