// Generated by LazyMagic - modifications will be overwritten

/// <summary>
/// Configuration for a Cognito User Pool authenticator
/// </summary>
public class AuthenticatorConfig
{
    /// <summary>
    /// The Cognito User Pool ID (e.g., us-east-1_ABC123)
    /// </summary>
    public string UserPoolId { get; set; } = string.Empty;

    /// <summary>
    /// The AWS Region where the User Pool is located (e.g., us-east-1)
    /// </summary>
    public string Region { get; set; } = string.Empty;
}
