// Generated by LazyMagic - modifications will be overwritten
public partial class Startup
{
    public Startup(IConfiguration configuration)
    {
        Configuration = configuration;
    }

    public static IConfiguration Configuration { get; private set; }

    // This method gets called to configure services. ConfigureSvcs will be generated.
    public void ConfigureServices(IServiceCollection services)
    {
        services.AddDefaultAWSOptions(Configuration.GetAWSOptions());
        ConfigureSvcs(services);
        services.AddControllers().AddNewtonsoftJson();
    }
}
