//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

namespace ChatModule
{
    /// <summary>
    /// Represents a file parameter for multipart form data uploads.
    /// </summary>
    public class FileParameter
    {
        public FileParameter(System.IO.Stream data, string fileName = null, string contentType = null)
        {
            Data = data;
            FileName = fileName;
            ContentType = contentType;
        }

        public System.IO.Stream Data { get; }
        public string FileName { get; }
        public string ContentType { get; }
    }
}
