//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

namespace ChatModule
{
    public partial interface IChatModuleClient
    {
        /// <summary>
        /// Create new chat session
        /// </summary>
        /// Creates a new chat session and starts processing the initial message
        /// </remarks>
        /// <returns>Session created successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<CreateSessionResponse> ChatModuleCreateSessionAsync(CreateSessionRequest body);

        /// <summary>
        /// Health check endpoint
        /// </summary>
        /// Health check endpoint for App Runner service monitoring
        /// </remarks>
        /// <returns>Service is healthy</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HealthCheckResponse> ChatModuleHealthCheckAsync();

        /// <summary>
        /// Send message to existing session
        /// </summary>
        /// Sends a message to an existing chat session
        /// </remarks>
        /// <param name="sessionId">ID of the chat session</param>
        /// <returns>Message sent successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SendMessageResponse> ChatModuleSendMessageAsync(string sessionId, SendMessageRequest body);

        /// <summary>
        /// Get session status
        /// </summary>
        /// Retrieves the current status and information about a chat session
        /// </remarks>
        /// <param name="sessionId">ID of the chat session</param>
        /// <returns>Session status retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetSessionStatusResponse> ChatModuleGetSessionStatusAsync(string sessionId);

        /// <summary>
        /// Close chat session
        /// </summary>
        /// Closes an active chat session and cleans up resources
        /// </remarks>
        /// <param name="sessionId">ID of the chat session to close</param>
        /// <returns>Session closed successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ChatModuleCloseSessionAsync(string sessionId);

        /// <summary>
        /// Get session message history
        /// </summary>
        /// Retrieves the message history for a chat session
        /// </remarks>
        /// <param name="sessionId">ID of the chat session</param>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of messages per page</param>
        /// <returns>Message history retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SessionMessagesResponse> ChatModuleGetSessionMessagesAsync(string sessionId, int? page, int? limit);
    }
}
