//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

namespace ChatModule
{
    public partial interface IChatModuleClient
    {
        /// <summary>
        /// Create new chat
        /// </summary>
        /// Creates a new chat session
        /// </remarks>
        /// <returns>Chat created successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Chat> ChatModuleAddChatAsync(Chat body);

        /// <summary>
        /// List chats
        /// </summary>
        /// Lists all chats for the authenticated user
        /// </remarks>
        /// <returns>Chats retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<Chat>> ChatModuleListChatsAsync();

        /// <summary>
        /// Health check endpoint
        /// </summary>
        /// Health check endpoint for service monitoring
        /// </remarks>
        /// <returns>Service is healthy</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HealthCheckResponse> ChatModuleHealthCheckAsync();

        /// <summary>
        /// Get chat by ID
        /// </summary>
        /// Retrieves a chat by its ID
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Chat retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Chat> ChatModuleGetChatByIdAsync(string chatId);

        /// <summary>
        /// Update chat
        /// </summary>
        /// Updates an existing chat
        /// </remarks>
        /// <param name="chatId">ID of the chat to update</param>
        /// <returns>Chat updated successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<Chat> ChatModuleUpdateChatAsync(string chatId, Chat body);

        /// <summary>
        /// Delete chat
        /// </summary>
        /// Deletes a chat and cleans up resources
        /// </remarks>
        /// <param name="chatId">ID of the chat to delete</param>
        /// <returns>Chat deleted successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ChatModuleDeleteChatAsync(string chatId);

        /// <summary>
        /// Send message to chat
        /// </summary>
        /// Sends a new message to an existing chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Message sent successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ChatMessage> ChatModuleAddChatMessageAsync(string chatId, ChatMessage body);

        /// <summary>
        /// Get chat messages
        /// </summary>
        /// Retrieves message history for a chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of messages per page</param>
        /// <returns>Messages retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<System.Collections.Generic.ICollection<ChatMessage>> ChatModuleGetChatMessagesAsync(string chatId, int? page, int? limit);
    }
}
