//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

namespace ChatModule
{
    public partial interface IChatModuleClient
    {
        /// <summary>
        /// Create new chat
        /// </summary>
        /// Creates a new chat and starts processing the initial message
        /// </remarks>
        /// <returns>Chat created successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<CreateChatResponse> ChatModuleCreateChatAsync(CreateChatRequest body);

        /// <summary>
        /// List chats
        /// </summary>
        /// Lists all chats for the authenticated user with pagination
        /// </remarks>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of chats per page</param>
        /// <param name="status">Filter by chat status</param>
        /// <returns>Chats retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ListChatsResponse> ChatModuleListChatsAsync(int? page, int? limit, ChatStatus? status);

        /// <summary>
        /// Health check endpoint
        /// </summary>
        /// Health check endpoint for App Runner service monitoring
        /// </remarks>
        /// <returns>Service is healthy</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<HealthCheckResponse> ChatModuleHealthCheckAsync();

        /// <summary>
        /// Send message to existing chat
        /// </summary>
        /// Sends a message to an existing chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Message sent successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<SendMessageResponse> ChatModuleSendMessageAsync(string chatId, SendMessageRequest body);

        /// <summary>
        /// Get chat status
        /// </summary>
        /// Retrieves the current status and information about a chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Chat status retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetChatStatusResponse> ChatModuleGetChatStatusAsync(string chatId);

        /// <summary>
        /// Get chat by ID
        /// </summary>
        /// Retrieves a chat by its ID from persistent storage
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <returns>Chat retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<GetChatResponse> ChatModuleGetChatAsync(string chatId);

        /// <summary>
        /// Update chat
        /// </summary>
        /// Updates chat metadata and status in persistent storage
        /// </remarks>
        /// <param name="chatId">ID of the chat to update</param>
        /// <returns>Chat updated successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<UpdateChatResponse> ChatModuleUpdateChatAsync(string chatId, UpdateChatRequest body);

        /// <summary>
        /// Close chat
        /// </summary>
        /// Closes an active chat and cleans up resources
        /// </remarks>
        /// <param name="chatId">ID of the chat to close</param>
        /// <returns>Chat closed successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task ChatModuleCloseChatAsync(string chatId);

        /// <summary>
        /// Get chat message history
        /// </summary>
        /// Retrieves the message history for a chat
        /// </remarks>
        /// <param name="chatId">ID of the chat</param>
        /// <param name="page">Page number for pagination</param>
        /// <param name="limit">Number of messages per page</param>
        /// <returns>Message history retrieved successfully</returns>
        /// <exception cref="ApiException">A server side error occurred.</exception>
        System.Threading.Tasks.Task<ChatMessagesResponse> ChatModuleGetChatMessagesAsync(string chatId, int? page, int? limit);
    }
}
