
//----------------------
// <auto-generated>
//     Generated by LazyMagic.
//     Do not modify, your changes will be overwritten.
//     This is a partial class so you can extend the class in a separate file.
//     Only files with *.g.* extensions will be overwritten.
// </auto-generated>
//----------------------

namespace ChatSchema
{
    using System = global::System;
    
#pragma warning disable CS1591 // Missing XML comment for publicly visible type or member
public partial class ChatContextModelValidator : FluentValidation.AbstractValidator<ChatContextModel>
{
    public ChatContextModelValidator()
    {
        Include(new ChatContextValidator());
        CustomValidation();
    }
    partial void CustomValidation();
}
#pragma warning restore CS1591 // Missing XML comment for publicly visible type or member

}
