//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using PublicModule;
using ConsumerModule;
using StoreModule;

namespace StoreApi
{
    public partial interface IStoreApi : IPublicModuleClient, IConsumerModuleClient, IStoreModuleClient
    {
        // All methods inherited from module client interfaces
    }
}