//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using ChatModule;
using PublicModule;
using ConsumerModule;
using StoreModule;
using AdminModule;

namespace StoreApi
{
    public partial interface IStoreApi : IChatModuleClient, IPublicModuleClient, IConsumerModuleClient, IStoreModuleClient, IAdminModuleClient
    {
        // All methods inherited from module client interfaces
    }
}