//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

using PublicModule;
using ConsumerModule;
using StoreModule;
using AdminModule;

namespace AdminApi
{
    public partial interface IAdminApi : IPublicModuleClient, IConsumerModuleClient, IStoreModuleClient, IAdminModuleClient
    {
        // All methods inherited from module client interfaces
    }
}