
// Generated by LazyMagic - modifications will be overwritten

public partial class Startup
{
    public void ConfigureSvcs(IServiceCollection services)
    {
        services.AddPublicModule();
		services.AddConsumerModule();
		services.AddStoreModule();
		services.AddAdminModule();
		services.AddChatModule();
    }
}
