
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace ChatSchemaRepo;
public partial interface IChatMessagesRepo : IDocumentRepo<ChatMessages> {}
public partial class ChatMessagesRepo : DYDBRepository<ChatMessages>, IChatMessagesRepo
{
    public ChatMessagesRepo(IAmazonDynamoDB client) : base(client) {}
}
