
//----------------------
// <auto-generated>
//  Generated by LazyMagic. Create overrides and partial method implementations in a separate file.
//  See the README.g.md file for best practices for extending these generated classes.
// </auto-generated>
//----------------------
namespace ChatSchemaRepo;
public partial interface IChatContextRepo : IDocumentRepo<ChatContext> {}
public partial class ChatContextRepo : DYDBRepository<ChatContext>, IChatContextRepo
{
    public ChatContextRepo(IAmazonDynamoDB client) : base(client) {}
}
