//----------------------
// <auto-generated>
//     Generated by LazyMagic, do not edit directly. Changes will be overwritten.
// </auto-generated>
//----------------------

namespace ApiAppRunnerDefault
{
    public partial interface IApiAppRunnerDefault
    {
        // No modules to inherit from
    }
}