// NSWAG code refactored by LazyMagic.
// We use NSWAG to generate a baseclass, partial class and interface. 
// I{ModuleName}Controller.g.cs - defines a partial interface
// {ModuleName}ControllerBase.g.cs - defines the base class
// {ModuleName}Controller.g.cs - defines a partial class that inherits the base class
// To add or override class behavior, create a new partial class file
// {projectName}Controller.cs - overrides methods in the base class
// Dependency Injection system.
// Note: We also generate some helper classes 
// {ModuleName}Authorization.g.cs - Partial class for Authorization system
// {ModuleName}Registration.g.cs - Registers classes with the DI system
//
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

namespace AdminModule
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "14.0.3.0 (NJsonSchema v11.0.0.0 (Newtonsoft.Json v13.0.0.0))")]

    public abstract class AdminModuleControllerBase : Controller, IAdminModuleController
    {

        /// <summary>
        /// Check if currently logged in tenantUser is an admin
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpGet, Route("AdminModule/isAdmin")]
        public virtual async Task<ActionResult<TenantUserStatus>> AdminModuleIsAdminAsync()
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// Add a new tenantUser
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpPost, Route("AdminModule/tenantUser")]
        public virtual async Task<ActionResult<TenantUser>> AdminModuleAddTenantUserAsync([FromBody] TenantUser body = null)
        {
            var callerInfo = await AdminModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await TenantUserRepo.CreateAsync(callerInfo, body);
        }
        /// <summary>
        /// Update an existing tenantUser
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpPut, Route("AdminModule/tenantUser")]
        public virtual async Task<ActionResult<TenantUser>> AdminModuleUpdateTenantUserAsync([FromBody] TenantUser body = null)
        {
            var callerInfo = await AdminModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await TenantUserRepo.UpdateAsync(callerInfo, body);
        }
        /// <summary>
        /// List all tenantUsers
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpGet, Route("AdminModule/tenantUser/listTenantUsers")]
        public virtual async Task<ActionResult<System.Collections.Generic.ICollection<TenantUser>>> AdminModuleListTenantUsersAsync()
        {
            var callerInfo = await AdminModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await TenantUserRepo.ListAsync(callerInfo);
        }
        /// <summary>
        /// Add a new Subtenant
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpPost, Route("AdminModule/subtenant")]
        public virtual async Task<ActionResult<Subtenant>> AdminModuleAddSubtenantAsync([FromBody] Subtenant body = null)
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// Update an existing Subtenant
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpPut, Route("AdminModule/subtenant")]
        public virtual async Task<ActionResult<Subtenant>> AdminModuleUpdateSubtenantAsync([FromBody] Subtenant body = null)
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// List all Subtenants
        /// </summary>
        /// <returns>successful operation</returns>
        [HttpGet, Route("AdminModule/subtenant/listSubtenants")]
        public virtual async Task<ActionResult<System.Collections.Generic.ICollection<Subtenant>>> AdminModuleListSubtenantsAsync()
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// See pet database
        /// </summary>
        /// <param name="numPets">Number of pets to seed</param>
        /// <param name="store">Store to seed</param>
        /// <returns>Success</returns>
        [HttpGet, Route("AdminModule/subtenant/seedPets/{store}/{numPets}")]
        public virtual async Task<IActionResult> AdminModuleSeedPetsAsync(int numPets, string store)
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// Suspend TenantUser
        /// </summary>
        /// <param name="tenantUser">tenantUser login</param>
        /// <returns>Success</returns>
        [HttpGet, Route("AdminModule/suspendTenantUser/{tenantUser}")]
        public virtual async Task<IActionResult> AdminModuleSuspendTenantUserAsync(string tenantUser)
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// Find tenantUser by ID
        /// </summary>
        /// <param name="tenantUserId">ID of tenantUser that needs to be fetched</param>
        /// <returns>successful operation</returns>
        [HttpGet, Route("AdminModule/tenantUser/{tenantUserId}")]
        public virtual async Task<ActionResult<TenantUser>> AdminModuleGetTenantUserByIdAsync(string tenantUserId)
        {
            var callerInfo = await AdminModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await TenantUserRepo.ReadAsync(callerInfo, tenantUserId);
        }
        /// <summary>
        /// Delete tenantUser by ID
        /// </summary>
        /// <param name="tenantUserId">ID of tenantUser that needs to be deleted</param>
        /// <returns>Success</returns>
        [HttpDelete, Route("AdminModule/tenantUser/delete/{tenantUserId}")]
        public virtual async Task<IActionResult> AdminModuleDeleteTenantUserAsync(string tenantUserId)
        {
            var callerInfo = await AdminModuleAuthorization.GetCallerInfoAsync(this.Request);
            return await TenantUserRepo.DeleteAsync(callerInfo, tenantUserId);
        }
        /// <summary>
        /// Find Subtenant by ID
        /// </summary>
        /// <param name="subtenantId">ID of Subtenant that needs to be fetched</param>
        /// <returns>successful operation</returns>
        [HttpGet, Route("AdminModule/subtenant/{subtenantId}")]
        public virtual async Task<ActionResult<Subtenant>> AdminModuleGetSubtenantByIdAsync(string subtenantId)
        {
            throw new NotImplementedException();
        }
        /// <summary>
        /// Delete Subtenant by ID
        /// </summary>
        /// <param name="subtenantId">ID of Subtenant that needs to be deleted</param>
        /// <returns>Success</returns>
        [HttpDelete, Route("AdminModule/subtenant/delete/{subtenantId}")]
        public virtual async Task<IActionResult> AdminModuleDeleteSubtenantAsync(string subtenantId)
        {
            throw new NotImplementedException();
        }
		public IAdminModuleAuthorization AdminModuleAuthorization { get; set; }
		public ITenantUserRepo TenantUserRepo { get; set; }
		protected virtual void Init() { }
    }


}
